version: '2'

services:
  front:
      container_name: front
      build:
        context: ./front
        args:
          - photoLocation=${PHOTO_LOCATION}
          - templocation=${TEMP_LOCATION}
          - previewImagePrefix=${PREVIEW_IMAGE_PREFIX}
      env_file:
        - '.env'
      ports:
        - "${NODE_PORT}:${NODE_PORT}"
      depends_on:
        - app
      links:
        - app
      volumes:
        - ./front/svg:/usr/src/app/svg
        - ./front/translations:/usr/src/app/translations
        - ./front/utils:/usr/src/app/utils
        - ./front/dev-server.js:/usr/src/app/dev-server.js
        - ./front/bin:/usr/src/app/bin
        - ./front/index.html:/usr/src/app/index.html
        - ./front/css:/usr/src/app/css

  app:
    container_name: app
    restart: always
    build: ./app
    ports:
      - "${API_PORT}:${API_PORT}"
      - 8000:8000
    depends_on:
      - db
    links:
      - db
    volumes:
       - ./${PHOTO_LOCATION}:/usr/local/tomcat/webapps/ROOT/${PHOTO_LOCATION}
       - ./${TEMP_LOCATION}:/usr/local/tomcat/webapps/ROOT/${TEMP_LOCATION}
    env_file:
       - '.env'

  db:
    container_name: db
    image: postgres:9.6
    volumes:
      - ./database/db:/var/lib/postgresql/data
      - ./database/script:/docker-entrypoint-initdb.d
    ports:
        - "5432:5432"
    environment:
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=root
        - POSTGRES_DB=cultivars
